name: Ultimate_Download
on:
  workflow_dispatch:

jobs:
  download_job:
    runs-on: ubuntu-latest
    steps:
      - name: Force Pull and Save
        run: |
          docker pull ctfhub/base_image_nginx_php_5.6
          docker save ctfhub/base_image_nginx_php_5.6 > ctfhub_image.tar
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-tar-file
          path: ctfhub_image.tar
