name: 100_PERCENT_SUCCESS
on: workflow_dispatch
jobs:
  get_image:
    runs-on: ubuntu-latest
    steps:
      - name: Official Docker Pull
        run: docker pull ctfhub/base_image_nginx_php_5.6
      - name: Export Image
        run: docker save ctfhub/base_image_nginx_php_5.6 > ctfhub.tar
      - name: Send to Browser
        uses: actions/upload-artifact@v4
        with:
          name: ctfhub-final-package
          path: ctfhub.tar
          retention-days: 1
